url: https://ldmss.github.io
enforce_ssl: ldmss.github.io
baseurl: ""

# Site settings
title: LDMSS
email: ldmss@protonmail.com
description: "Learning and decision making summer school for cognitive and behavioural scientists."


# Team names, titles and social links
directors:
- name: Pantelis P. Analytis
  pic: 2
  position: University of Southern Denmark
  social:
    - title: home
      url: https://danish-ias.dk/people/pantelis-pipergias-analytis/
    - title: envelope
      url: mailto:pantelis@sam.sdu.dk
    - title: twitter
      url: https://twitter.com/pantelispa
- name: Emmanouil Konstantinidis
  pic: 3
  position: University of Warwick
  social:
    - title: home
      url: https://business.leeds.ac.uk/divisions-management/staff/320/dr-emmanouil-konstantinidis
    - title: envelope
      url: mailto:E.Konstantinidis@leeds.ac.uk
    - title: twitter
      url: https://twitter.com/manoskon
- name: Hrvoje Stojic
  pic: 1
  position: Secondmind
  social:
    - title: home
      url: http://hstojic.re
    - title: envelope
      url: mailto:hrvoje.stojic@protonmail.com
    - title: twitter
      url: https://twitter.com/HrvojeStojic
- name: Mikhail Spektor
  pic: 4
  position: Universitat Pompeu Fabra
  social:
    - title: home
      url: https://msspektor.github.io/
    - title: envelope
      url: mailto:mikhail.spektor@upf.edu
    - title: twitter
      url: https://twitter.com/SpektorMikhail
- name: Gael Le Mens
  pic: 5
  position: Universitat Pompeu Fabra
  social:
    - title: home
      url: https://sites.google.com/view/gael-le-mens/
    - title: envelope
      url: mailto:gael.lemens@upf.edu

faculty:
- name: Gael Le Mens
  pic: 5
  position: Universitat Pompeu Fabra
  social:
    - title: home
      url: https://sites.google.com/view/gael-le-mens/
    - title: envelope
      url: mailto:gael.lemens@upf.edu
- name: Maarten Speekenbrink
  pic: 8
  position: University College London
  social:
    - title: home
      url: https://speekenbrink-lab.github.io/
    - title: envelope
      url: mailto:m.speekenbrink@ucl.ac.uk
    - title: twitter
      url: https://twitter.com/MaartenSpeek  
- name: Kinneret Teodorescu
  pic: 16
  position: Technion - Israel Institute of Technology
  social:
    - title: home
      url: https://web.iem.technion.ac.il/site/academicstaff/kinneret-teodorescu/
    - title: envelope
      url: mailto:kinnerett@technion.ac.il
- name: Emmanouil Konstantinidis
  pic: 3
  position: University of Warwick
  social:
    - title: home
      url: https://business.leeds.ac.uk/divisions-management/staff/320/dr-emmanouil-konstantinidis
    - title: envelope
      url: mailto:E.Konstantinidis@leeds.ac.uk
    - title: twitter
      url: https://twitter.com/manoskon
- name: Antonia Krefeld-Schwalb
  pic: 15
  position: Rotterdam School of Management - Erasmus University
  social:
    - title: home
      url: https://www.antoniakrefeldschwalb.com/
    - title: envelope
      url: mailto:a.krefeldschwalb@gmail.com
    - title: twitter
      url: https://twitter.com/@AntoniaKrefeld
- name: Hrvoje Stojic
  pic: 1
  position: University College London
  social:
    - title: home
      url: http://hstojic.re
    - title: envelope
      url: mailto:hrvoje.stojic@protonmail.com
    - title: twitter
      url: https://twitter.com/HrvojeStojic
- name: Pantelis P. Analytis
  pic: 2
  position: University of Southern Denmark
  social:
    - title: home
      url: https://danish-ias.dk/people/pantelis-pipergias-analytis/
    - title: envelope
      url: mailto:pantelis@sam.sdu.dk
    - title: twitter
      url: https://twitter.com/pantelispa
- name: Mikhail Spektor
  pic: 4
  position: Universitat Pompeu Fabra
  social:
    - title: home
      url: https://msspektor.github.io/
    - title: envelope
      url: mailto:mikhail.spektor@upf.edu
    - title: twitter
      url: https://twitter.com/SpektorMikhail

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ldmss
  
# Postal address (add as many lines as necessary)
address:
  - line: #
  - line: #

# Build settings
markdown: kramdown
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md 
  - .gitignore
